# This file configures the static analysis results for your project.

# For more information, see:
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  # This is the section where we can customize analysis rules.
  errors:
    # We are telling the analyzer to treat the 'unused_element_parameter' rule
    # as completely ignored, but ONLY for files that end with '.g.dart'.
    # This will solve the error from your retrofit generated file.
    unused_element_parameter: ignore

linter:
  # You can specify additional lint rules here if you want.
  # For example:
  rules:
  # prefer_const_constructors: true
  # avoid_print: true
