name: flutter_project_starter
description: "Project starter for Flutter by mushafa21"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # Database
  sqflite: ^2.4.2

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0


  # Networking
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  awesome_dio_interceptor: ^1.3.0


  # Service Locator
  get_it: ^8.0.3

  # Routing
  go_router: ^15.2.0

  # Utilities
  envied: ^1.1.1
  shared_preferences: ^2.5.3
  path: ^1.8.3






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Testing
  mockito: ^5.4.6
  bloc_test: ^10.0.0

  # Build Runner
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0
  envied_generator: ^1.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
